### ISSUE TITLE
cmake build error

### ISSUE THREAD

**Issue by walter211** [epezent/implot_demos#1]
error:
      expected expression
    style.WindowPadding = {6,6};

**Comment by walter211** [comment]
/Users/3x1/Documents/GitHub/root/implot_demos/common/App.cpp:14:27: error:
      expected expression
    style.WindowPadding = {6,6};
                          ^
/Users/3x1/Documents/GitHub/root/implot_demos/common/App.cpp:15:27: error:
      expected expression
    style.FramePadding  = {6,3};
                          ^
/Users/3x1/Documents/GitHub/root/implot_demos/common/App.cpp:16:27: error:
      expected expression
    style.CellPadding   = {6,3};
                          ^
/Users/3x1/Documents/GitHub/root/implot_demos/common/App.cpp:17:27: error:
      expected expression
    style.ItemSpacing   = {6,6};
                          ^
/Users/3x1/Documents/GitHub/root/implot_demos/common/App.cpp:18:30: error:
      expected expression
    style.ItemInnerSpacing = {6,6};
                             ^
/Users/3x1/Documents/GitHub/root/implot_demos/common/App.cpp:64:12: error:
      use of undeclared identifier 'ImGuiCol_DockingPreview'
    colors[ImGuiCol_DockingPreview]         = ImVec4(0.85f, 0.85f, 0....
           ^
/Users/3x1/Documents/GitHub/root/implot_demos/common/App.cpp:65:12: error:
      use of undeclared identifier 'ImGuiCol_DockingEmptyBg'
    colors[ImGuiCol_DockingEmptyBg]         = ImVec4(0.38f, 0.38f, 0....
           ^
/Users/3x1/Documents/GitHub/root/implot_demos/common/App.cpp:110:5: warning:
      'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    auto& pstyle = ImPlot::GetStyle();
    ^
/Users/3x1/Documents/GitHub/root/implot_demos/common/App.cpp:111:49: error:
      expected expression
    pstyle.PlotPadding = pstyle.LegendPadding = {12,12};
                                                ^
/Users/3x1/Documents/GitHub/root/implot_demos/common/App.cpp:112:55: error:
      expected expression
    pstyle.LabelPadding = pstyle.LegendInnerPadding = {6,6};
                                                      ^
/Users/3x1/Documents/GitHub/root/implot_demos/common/App.cpp:113:28: error:
      expected expression
    pstyle.LegendSpacing = {2,2};

**Comment by walter211** [comment]
after add 
`set_property(TARGET app PROPERTY CXX_STANDARD 17)`
at line 99
compiler showing below：



/Users/3x1/Documents/GitHub/root/implot_demos/common/App.cpp:64:12: error: use of undeclared identifier
      'ImGuiCol_DockingPreview'
    colors[ImGuiCol_DockingPreview]         = ImVec4(0.85f, 0.85f, 0.85f, 0.28f);
           ^
/Users/3x1/Documents/GitHub/root/implot_demos/common/App.cpp:65:12: error: use of undeclared identifier
      'ImGuiCol_DockingEmptyBg'
    colors[ImGuiCol_DockingEmptyBg]         = ImVec4(0.38f, 0.38f, 0.38f, 1.00f);
           ^

**Comment by jsc-paneda** [comment]
Was just attempting to build this also and I get same error as your last one (did not make any edits of CMakeLists.txt).

**Comment by walter211** [comment]
> Was just attempting to build this also and I get same error as your last one (did not make any edits of CMakeLists.txt).

it seems implot version need to be indicated.

**Comment by walter211** [comment]
what r u using this for? I am trying to transfer this project to wasm.

**Comment by jsc-paneda** [comment]
I'm looking to develop a very graph/plot intensive app and just discovered ImGui/ImPlot. Been using QT charts but they need lots of code behind to get the behaviour I want. ImPlot plots looks amazing out of the box! I now got it compiling/working using [mahi-gui](https://github.com/mahilab/mahi-gui) so I#m good at the moment.

**Comment by walter211** [comment]
> I'm looking to develop a very graph/plot intensive app and just discovered ImGui/ImPlot. Been using QT charts but they need lots of code behind to get the behaviour I want. ImPlot plots looks amazing out of the box! I now got it compiling/working using [mahi-gui](https://github.com/mahilab/mahi-gui) so I#m good at the moment.

Same senerio as u. I agree with u,  launched mahi-gui succesed before, I will keep eyes on this project.

**Comment by epezent** [comment]
I've handled the styling of dock related items if IMGUI_HAS_DOCK is not defined. Closing the issue.
