### ISSUE TITLE
Does not build with latest ImGui (v1.84)

### ISSUE THREAD

**Issue by Green-Sky** [epezent/implot_demos#3]
ImGui v1.84 removed there gl3w code, because it is now embeded.
... also, having to have imgui and implot be in the directory above is kinda bad, imho.

**Comment by epezent** [comment]
Thanks for the heads up. Regarding the folder structure, I use this approach because it is convenient for simultaneous development with ImPlot. In fact, this repo sort of serves as my "test" framework for ImPlot, for better or worse. I may look for alternative solutions in the future.
