### ISSUE TITLE
How to plot scrolling spectrogram efficiently ?

### ISSUE THREAD

**Issue by anup-das** [epezent/implot_demos#8]
I am using ImPlot to plot the spectrogram of audio recorded from microphone in real-time and it works fine. It is based on the demo in this repo.

What would be the most efficient way to have the plot scroll in real-time with new data entering from the right ?

I tried using ImPlotHeatmapFlags_ColMajor so as to have the spectrogram bins in consecutive memory in C/C++  with the idea of doing some movement of elements in the array. But I was unable to get ImPlotHeatmapFlags_ColMajor to work correctly.  I only changed the order of data in the array and enabled the flag with no other change. 

BTW thanks for developing the awesome ImPlot library

**Comment by marcizhu** [comment]
The [spectrogram demo](https://github.com/epezent/implot_demos/blob/master/demos/spectrogram.cpp) does exactly what you are looking for. It's a 2D heatmap with data entering fron the right continuously.

**Comment by anup-das** [comment]
I should have explained properly. The demo has access to future samples (as it plays from a file) and it also recomputes entire N_BINs of FFT every time. I don't want to recompute FFT that was previously computed. I think this can be achieved using column major plotting and discarding a portion of the old data. 

I need help in getting column major to work correctly. I modified the following lines in the demo but the output is not correct. See attached
![image](https://user-images.githubusercontent.com/63170829/187014389-5f9a1e54-25ae-47af-96be-25f8e1258ecb.png)


# Change 1 -- Added the ImPlotHeatmapFlags_ColMajor flag and swapped positions of N_BIN and NFRQ (rows and columns) variables in the line 

ImPlot::PlotHeatmap("##Heat",m_spectrogram.data(),N_BIN,N_FRQ,m_min_db,m_max_db,NULL,{tmin,0},{tmax,m_fft_frq[N_FRQ-1]/1000}, ImPlotHeatmapFlags_ColMajor);

#2 Change - store data in vector in column major format
m_spectrogram[b*N_FRQ+f] = 20*log10f(std::abs(m_fft_out[N_FRQ-1-f]));

**Comment by anup-das** [comment]
If i do not swap the row and column variables N_BIN and N_FRQ then i get distorted output
![image](https://user-images.githubusercontent.com/63170829/187015727-44164f2c-da49-461b-82dc-ca971cbadba6.png)
